# recruiter-platform/docker-compose.yml

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
      - ./backend/alembic.ini:/app/alembic.ini
      # --- START: THIS IS THE FIX ---
      # Update the paths to reflect the new location of the agent files
      # inside the 'backend/app/services' directory.
      - ./backend/app/services/test_searcher.py:/app/app/services/test_searcher.py
      - ./backend/app/services/ranker.py:/app/app/services/ranker.py
      # --- END: THIS IS THE FIX ---

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      # Sync your local frontend code with the container
      - ./frontend:/app
      # Use a named volume to isolate node_modules inside the container
      - node_modules:/app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

# Defines the named volume we used above.
volumes:
  node_modules: